### ISSUE TITLE
[FIXED?] Missing tooltips

### ISSUE THREAD

**Issue by HeinOldewage** [ZwerOxotnik/rpg_items#3]
Please drop the `factorio-current.log` file or `factorio-previous.log` here
[factorio-current.log](https://github.com/ZwerOxotnik/rpg_items/files/10032672/factorio-current.log)

**Describe the bug**

After buying an additional item slot, all the tooltips of the other items were empty

**Steps to reproduce**
Running `/c __m-rpg_items__ create_equipment_gui(game.get_player(1))` in the console should reproduce the issue
Or buying a bonus item slot should cause the issue. 

**Expected behavior**
Items normal tooltips should show.

**Screenshots/Videos (If you have any)**

![Untitled](https://user-images.githubusercontent.com/73693344/202480527-8b77bca1-2670-45b0-97cd-93dbbd1b2845.png)

**Additional Information**
Add any other context about the problem here?

I think the issue is in rpg_items\rpg_framework.lua:1386, where the tooltip is constructed from `data`, rather than `item`

**Comment by ZwerOxotnik** [comment]
I'll fix it in ~3 minutes

**Comment by ZwerOxotnik** [comment]
It'll take a bit more time to update.

**Comment by ZwerOxotnik** [comment]
@HeinOldewage, updated [https://mods.factorio.com/mod/m-rpg_items/downloads](https://mods.factorio.com/mod/m-rpg_items/downloads)  
It should show it now.

**Comment by HeinOldewage** [comment]
The update is now visible in the game's mod manager.

Loading an existing save still has the issue, but running `/c __m-rpg_items__ create_equipment_gui(game.get_player(1))` made it display the correct values. 
Not sure a migration is needed, so we can close the issue.

Thanks for the great support.
